export default {
  LOGIN_USER: '/user/login',
  GET_WAREHOUSE_DATA: '/warehouse/all?page=0&perPage=50',
  CREATE_WAREHOUSE: '/warehouse/',
  GET_USERS_DATA: '/user/all?page=0&perPage=10',
  GET_ROLES_DATA: '/user-role/all?page=0&perPage=10',
  GET_CHILDREN_FROM_PARENT: '/dashboard/get-children-from-parent',
  ADD_NEW_ZONE: '/zone',
  ADD_NEW_AREA: '/area',
  ADD_NEW_ROW: '/row',
  ADD_NEW_BAY: '/bay',
  ADD_NEW_LEVEL: '/level',
  ADD_NEW_SUBLEVEL: '/sublevel',
  ADD_ITEM: '/item/',
  EDIT_ITEM: '/item/',
  ADD_INVENTORY: '/inventory',
  GET_INVENTORY: '/inventory/all?page=0&perPage=50',
  GET_INVENTORY_TYPES: '/inventory/types',
  LOCATION_DELETE: '/dashboard/delete-location',
  GET_WIDGET_FAMILY_BY_INVENTORY: '/widget-family/search-by-inventory?inventory=',
  ADD_WIDGET_FAMILY: '/widget-family',
  EDIT_WIDGET_FAMILY: '/widget-family/',
  GET_ITEMS_BY_INVENTORY: '/item/filter?inventory='
};
